import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { DiagnosisResult } from '../types';

export async function generatePDF(diagnosis: DiagnosisResult): Promise<void> {
  try {
    // Create a temporary container with the report content
    const container = document.createElement('div');
    container.style.position = 'fixed';
    container.style.left = '-9999px';
    container.style.top = '-9999px';
    container.style.width = '1200px';
    container.style.padding = '40px';
    container.style.backgroundColor = '#ffffff';
    container.style.fontFamily = 'Arial, sans-serif';
    container.style.color = '#333333';

    // Build the HTML content
    container.innerHTML = `
      <div style="text-align: center; margin-bottom: 40px; border-bottom: 3px solid #1a472a; padding-bottom: 20px;">
        <h1 style="font-size: 32px; color: #1a472a; margin: 0 0 10px 0;">Plant Disease Diagnosis Report</h1>
        <p style="color: #666; font-size: 12px; margin: 0;">Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}</p>
      </div>

      <div style="margin-bottom: 30px;">
        <h2 style="font-size: 24px; color: #1a472a; margin-bottom: 15px;">Analysis Results</h2>
        
        <div style="background: ${getSeverityBg(diagnosis.disease.severity)}; border: 2px solid ${getSeverityBorder(diagnosis.disease.severity)}; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="font-size: 22px; color: #1a472a; margin: 0 0 10px 0;">Disease Identified</h3>
          <p style="font-size: 28px; font-weight: bold; color: ${getSeverityColor(diagnosis.disease.severity)}; margin: 0;">${diagnosis.disease.name}</p>
          <p style="font-size: 14px; color: #666; margin: 10px 0 0 0;">Severity: <strong>${diagnosis.disease.severity.charAt(0).toUpperCase() + diagnosis.disease.severity.slice(1)}</strong></p>
        </div>

        <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h4 style="font-size: 16px; color: #1a472a; margin: 0 0 10px 0;">Plant Type</h4>
          <p style="margin: 0; font-size: 14px;">${diagnosis.disease.plantType}</p>
        </div>

        <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h4 style="font-size: 16px; color: #1a472a; margin: 0 0 10px 0;">Confidence Level</h4>
          <div style="font-size: 28px; font-weight: bold; color: ${getConfidenceColor(diagnosis.confidence)}; margin-bottom: 10px;">${(diagnosis.confidence * 100).toFixed(1)}%</div>
          <p style="margin: 0; font-size: 12px; color: #666;">
            ${diagnosis.confidence >= 0.8 ? 'High confidence: This diagnosis is very reliable based on the image analysis.' : ''}
            ${diagnosis.confidence >= 0.6 && diagnosis.confidence < 0.8 ? 'Moderate confidence: This is a likely diagnosis, but cross-reference with other symptoms.' : ''}
            ${diagnosis.confidence < 0.6 ? 'Lower confidence: For best results, take a clearer photo and try again.' : ''}
          </p>
        </div>
      </div>

      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 18px; color: #1a472a; margin-bottom: 10px;">Disease Description</h3>
        <p style="margin: 0; font-size: 13px; line-height: 1.6; color: #333;">${diagnosis.disease.description}</p>
      </div>

      <div style="margin-bottom: 30px;">
        <h3 style="font-size: 18px; color: #1a472a; margin-bottom: 10px;">Common Symptoms</h3>
        <ul style="margin: 0; padding-left: 20px; font-size: 13px;">
          ${diagnosis.disease.symptoms.map((symptom) => `<li style="margin-bottom: 5px;">${symptom}</li>`).join('')}
        </ul>
      </div>

      <div style="background: #e8f5e9; border: 2px solid #4caf50; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
        <h3 style="font-size: 18px; color: #1a472a; margin: 0 0 10px 0;">Treatment & Management</h3>
        <p style="margin: 0; font-size: 13px; line-height: 1.6; color: #333;">${diagnosis.disease.treatment}</p>
      </div>

      <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 11px;">
        <p style="margin: 0;">This report was generated by PlantDoc AI. For professional agricultural advice, consult with a plant pathologist.</p>
        <p style="margin: 5px 0 0 0;">Report ID: ${new Date().getTime()}</p>
      </div>
    `;

    document.body.appendChild(container);

    // Convert to canvas
    const canvas = await html2canvas(container, {
      backgroundColor: '#ffffff',
      scale: 2,
    });

    // Remove temporary container
    document.body.removeChild(container);

    // Create PDF from canvas
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 210; // A4 width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const pdf = new jsPDF({
      orientation: imgHeight > imgWidth ? 'portrait' : 'landscape',
      unit: 'mm',
      format: 'a4',
    });

    const pageHeight = pdf.internal.pageSize.getHeight();
    const pageWidth = pdf.internal.pageSize.getWidth();
    let heightLeft = imgHeight;
    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Download PDF
    pdf.save(`plant-diagnosis-${new Date().getTime()}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report');
  }
}

function getSeverityColor(severity: string): string {
  switch (severity) {
    case 'high':
      return '#d32f2f';
    case 'medium':
      return '#f57c00';
    case 'low':
      return '#388e3c';
    default:
      return '#1a472a';
  }
}

function getSeverityBg(severity: string): string {
  switch (severity) {
    case 'high':
      return '#ffebee';
    case 'medium':
      return '#fff3e0';
    case 'low':
      return '#e8f5e9';
    default:
      return '#f5f5f5';
  }
}

function getSeverityBorder(severity: string): string {
  switch (severity) {
    case 'high':
      return '#ef5350';
    case 'medium':
      return '#ffb74d';
    case 'low':
      return '#81c784';
    default:
      return '#bdbdbd';
  }
}

function getConfidenceColor(confidence: number): string {
  if (confidence >= 0.8) return '#388e3c';
  if (confidence >= 0.6) return '#f57c00';
  return '#d32f2f';
}
